### ISSUE TITLE
RuntimeError: std::bad_alloc

### ISSUE THREAD

**Issue by tljk** [facebookresearch/banmo#10]
Optimization failed when the memory is available
our setup rtx2080ti * 2, Intel(R) Core(TM) i9-10900X CPU @ 3.70GHz, 32GB memory
log file attached

`/home/hyang/.conda/envs/banmo-cu113/lib/python3.9/site-packages/numpy/core/fromnumeric.py:3440: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/hyang/.conda/envs/banmo-cu113/lib/python3.9/site-packages/numpy/core/_methods.py:189: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
/home/hyang/.conda/envs/banmo-cu113/lib/python3.9/site-packages/numpy/core/fromnumeric.py:3440: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/hyang/.conda/envs/banmo-cu113/lib/python3.9/site-packages/numpy/core/_methods.py:189: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
Traceback (most recent call last):
  File "/mnt/banmo/main.py", line 42, in <module>
    app.run(main)
  File "/home/hyang/.conda/envs/banmo-cu113/lib/python3.9/site-packages/absl/app.py", line 312, in run
    _run_main(main, args)
  File "/home/hyang/.conda/envs/banmo-cu113/lib/python3.9/site-packages/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "/mnt/banmo/main.py", line 39, in main
    trainer.train()
  File "/mnt/banmo/nnutils/train_utils.py", line 684, in train
    self.train_one_epoch(epoch, log)
  File "/mnt/banmo/nnutils/train_utils.py", line 922, in train_one_epoch
    total_loss,aux_out = self.model(batch)
  File "/home/hyang/.conda/envs/banmo-cu113/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/hyang/.conda/envs/banmo-cu113/lib/python3.9/site-packages/torch/nn/parallel/distributed.py", line 886, in forward
    output = self.module(*inputs[0], **kwargs[0])
  File "/home/hyang/.conda/envs/banmo-cu113/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/mnt/banmo/nnutils/banmo.py", line 650, in forward_default
    mesh_rest = pytorch3d.structures.meshes.Meshes(
  File "/mnt/banmo/third_party/pytorch3d/pytorch3d/structures/meshes.py", line 406, in __init__
    if len(self._num_faces_per_mesh.unique()) == 1:
  File "/home/hyang/.conda/envs/banmo-cu113/lib/python3.9/site-packages/torch/_tensor.py", line 530, in unique
    return torch.unique(self, sorted=sorted, return_inverse=return_inverse, return_counts=return_counts, dim=dim)
  File "/home/hyang/.conda/envs/banmo-cu113/lib/python3.9/site-packages/torch/_jit_internal.py", line 422, in fn
    return if_false(*args, **kwargs)
  File "/home/hyang/.conda/envs/banmo-cu113/lib/python3.9/site-packages/torch/_jit_internal.py", line 422, in fn
    return if_false(*args, **kwargs)
  File "/home/hyang/.conda/envs/banmo-cu113/lib/python3.9/site-packages/torch/functional.py", line 821, in _return_output
    output, _, _ = _unique_impl(input, sorted, return_inverse, return_counts, dim)
  File "/home/hyang/.conda/envs/banmo-cu113/lib/python3.9/site-packages/torch/functional.py", line 735, in _unique_impl
    output, inverse_indices, counts = torch._unique2(
RuntimeError: std::bad_alloc
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 32696 closing signal SIGTERM
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 1 (pid: 32697) of binary: /home/hyang/.conda/envs/banmo-cu113/bin/python
Traceback (most recent call last):
  File "/home/hyang/.conda/envs/banmo-cu113/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/hyang/.conda/envs/banmo-cu113/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/hyang/.conda/envs/banmo-cu113/lib/python3.9/site-packages/torch/distributed/launch.py", line 193, in <module>
    main()
  File "/home/hyang/.conda/envs/banmo-cu113/lib/python3.9/site-packages/torch/distributed/launch.py", line 189, in main
    launch(args)
  File "/home/hyang/.conda/envs/banmo-cu113/lib/python3.9/site-packages/torch/distributed/launch.py", line 174, in launch
    run(args)
  File "/home/hyang/.conda/envs/banmo-cu113/lib/python3.9/site-packages/torch/distributed/run.py", line 710, in run
    elastic_launch(
  File "/home/hyang/.conda/envs/banmo-cu113/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/hyang/.conda/envs/banmo-cu113/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 259, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: `
[log.log](https://github.com/facebookresearch/banmo/files/8311168/log.log)

**Comment by gengshan-y** [comment]
See https://github.com/facebookresearch/banmo/issues/4#issuecomment-1065203673
