### ISSUE TITLE
some bugs, when I render the results

### ISSUE THREAD

**Issue by linxia1997** [facebookresearch/banmo#5]
Thanks for your great jobs.
There are some bugs when I render the results using pyrender.
My version of ubuntu is 20.04, and install all library according to your banmo.yml
the backtrack of error logger is:
```
libEGL warning: DRI2: failed to create dri screen
libEGL warning: DRI2: failed to create dri screen
Traceback (most recent call last):
  File "scripts/visualize/render_vis.py", line 537, in <module>
    main()
  File "scripts/visualize/render_vis.py", line 329, in main
    r = OffscreenRenderer(img_size, img_size)
  File "/home/linxia/anaconda3/envs/banmo/lib/python3.8/site-packages/pyrender/offscreen.py", line 31, in __init__
    self._create()
  File "/home/linxia/anaconda3/envs/banmo/lib/python3.8/site-packages/pyrender/offscreen.py", line 149, in _create
    self._platform.init_context()
  File "/home/linxia/anaconda3/envs/banmo/lib/python3.8/site-packages/pyrender/platforms/egl.py", line 177, in init_context
    assert eglInitialize(self._egl_display, major, minor)
  File "/home/linxia/anaconda3/envs/banmo/lib/python3.8/site-packages/OpenGL/platform/baseplatform.py", line 402, in __call__
    return self( *args, **named )
  File "/home/linxia/anaconda3/envs/banmo/lib/python3.8/site-packages/OpenGL/error.py", line 228, in glCheckError
    raise GLError(
OpenGL.error.GLError: GLError(
        err = 12289,
        baseOperation = eglInitialize,
        cArguments = (
                <OpenGL._opaque.EGLDisplay_pointer object at 0x7fad0deeb040>,
                c_long(0),
                c_long(0),
        ),
        result = 0
)
```
I don't know how to fix it.
If I change 'egl' to 'osmesa', which is too slow as it is cpu-only.

**Comment by gengshan-y** [comment]
You may run scripts with `EGL_DEVICE_ID=-1 bash xxx.sh`, or add `export EGL_DEVICE_ID=-1` to bashrc file. This makes sure egl to get an empty device [during pyrender initialization](https://github.com/mmatl/pyrender/blob/4a289a6205c5baa623cd0e7da1be3d898bcbc4da/pyrender/offscreen.py#L136).

**Comment by linxia1997** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by linxia1997** [comment]
It works well. thanks
