### ISSUE TITLE
issue of "tmp/nvs-5-0-traj-all.mp4: No such file or directory" when trying pre-optimized models

### ISSUE THREAD

**Issue by zhuqr1996** [facebookresearch/banmo#54]
Thank you for bringing the fascinating work! I am trying it with CUDA 113, torch 1.10 and and met some problems:

The situation arises when I tried to render novel views with the command for trying pre-optimized model:  "bash scripts/render_nvs.sh 0 $seqname tmp/cat-pikachiu.pth 5 0"

It looks super similar to #16 (seen in attached figure) but the error is different . Mine is IndexError: index 0 is out of bounds for axis 0 with size 0 (also attached) which I think might be not the same reason so I have not tried to create the Version B with torch 1.7 yet. 

Another situation is it said "tmp/cat-pikachiu-{5}-vgray.mp4: No such file or directory" while it exists in the doc file. But the all.mp4 is not there.

The log file is also attached.

![error](https://user-images.githubusercontent.com/52146447/234271437-efc30813-d36d-4523-9c30-bb9d4c881d68.png)
![error2](https://user-images.githubusercontent.com/52146447/234271440-e6664b62-3e3c-4371-927a-f64431a302b8.png)
![doc file](https://user-images.githubusercontent.com/52146447/234271433-63738fe5-6842-4f09-a6a2-fc283d0db8b9.png)
[log.txt](https://github.com/facebookresearch/banmo/files/11322314/log.txt)

**Comment by gengshan-y** [comment]
Hi, from the log you posted, the first error is 
```
Traceback (most recent call last):
  File "/root/banmo/scripts/visualize/render_vis.py", line 538, in <module>
    main()
  File "/root/banmo/scripts/visualize/render_vis.py", line 330, in main
    r = OffscreenRenderer(img_size, img_size)
  File "/opt/conda/envs/banmo-cu113/lib/python3.9/site-packages/pyrender/offscreen.py", line 31, in __init__
    self._create()
  File "/opt/conda/envs/banmo-cu113/lib/python3.9/site-packages/pyrender/offscreen.py", line 149, in _create
    self._platform.init_context()
  File "/opt/conda/envs/banmo-cu113/lib/python3.9/site-packages/pyrender/platforms/egl.py", line 186, in init_context
    self._egl_context = eglCreateContext(
  File "/opt/conda/envs/banmo-cu113/lib/python3.9/site-packages/OpenGL/platform/baseplatform.py", line 402, in __call__
    return self( *args, **named )
  File "/opt/conda/envs/banmo-cu113/lib/python3.9/site-packages/OpenGL/error.py", line 228, in glCheckError
    raise GLError(
OpenGL.error.GLError: GLError(
        err = 12297,
        baseOperation = eglCreateContext,
        cArguments = (
                <OpenGL._opaque.EGLDisplay_pointer object at 0x7fc38720d3c0>,
                <OpenGL._opaque.EGLConfig_pointer object at 0x7fc38720d440>,
                <OpenGL._opaque.EGLContext_pointer object at 0x7fc4a2b83b40>,
                <OpenGL.arrays.lists.c_int_Array_7 object at 0x7fc4a2ca8940>,
        ),
        result = <OpenGL._opaque.EGLContext_pointer object at 0x7fc38720d9c0>
)
```
which is related to pyrender package. The error code is the same as [this issue](https://github.com/mkocabas/VIBE/issues/148#issuecomment-759261580). You might want to try their solution and make sure 
 ```
import pyrender
from pyrender import OffscreenRenderer
r = OffscreenRenderer(img_size, img_size)
```
runs.

**Comment by zhuqr1996** [comment]
Thank you for the reply but sadly it still not work. 
When I tried the line of "bash scripts/render_nvs.sh 0 $seqname tmp/cat-pikachiu.pth 5 0", the mesh is not found. I checked the render_vis.py document, but the used obj files exist in the folder and I could understand why the mesh is not created.
The log for this time is attached again. [log2.txt](https://github.com/facebookresearch/banmo/files/11551139/log2.txt)

**Comment by gengshan-y** [comment]
Hi, the log suggests it cannot find `tmp/cat-pikachiu00-mesh-00000.obj` file. However, the mesh should be export to that location at [this line](https://github.com/facebookresearch/banmo/blob/d2ac32470c1cfb2542f354ac4024403509409df6/extract.py#L52). 

I was not able to reproduce it. Perhaps you want to check whether the path matches by printing it.

**Comment by zhuqr1996** [comment]
Thank you for the response. my own animal model can be perfectly generated thanks to your great work. And I wonder is the generated model able to be saved in specific document forms(namely .obj) which can later show in 3D software like Blender or Maya?

**Comment by gengshan-y** [comment]
Hi, I wrote some code in the past to convert banmo output (rest mesh, bone transforms and skinning weights) to [.gltf/.glb format](https://github.com/KhronosGroup/glTF), which can be visualized in Blender or on a web viewer. Ideally, I can release it if I get some time to clean it up in the next couple of weeks.

**Comment by LyndzP** [comment]
@gengshan-y  Hello, I appreciate you taking the time for this project. If possible, could you spare a moment to create a clean code that converts to the glTF format? This project is truly outstanding! Once again, thank you for your effort.
